# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
use = ""

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered = { fg = "black", bg = "magenta" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightyellow", bg = "lightyellow" }
marker_selected = { fg = "lightblue",   bg = "lightblue" }

# Tab
tab_active   = { fg = "black", bg = "white" }
tab_inactive = { fg = "white", bg = "darkgray" }
tab_width    = 1

# Count
count_copied   = { fg = "black", bg = "lightgreen" }
count_cut      = { fg = "black", bg = "lightred" }
count_selected = { fg = "black", bg = "lightblue" }

# Border
border_symbol = "│"
border_style  = { fg = "gray" }

# Highlighting
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "darkgray", bg = "darkgray" }

# Mode
mode_normal = { fg = "black", bg = "magenta", bold = true }
mode_select = { fg = "black", bg = "lightgreen", bold = true }
mode_unset  = { fg = "black", bg = "lightmagenta", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "lightgreen" }
permissions_r = { fg = "lightyellow" }
permissions_w = { fg = "lightred" }
permissions_x = { fg = "lightcyan" }
permissions_s = { fg = "darkgray" }


[select]
border   = { fg = "blue" }
active   = { fg = "magenta" }
inactive = {}

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "blue" }
active   = { bg = "darkgray" }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { underline = true }

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "magenta" }
separator       = "  "
separator_style = { fg = "darkgray" }


[help]
on      = { fg = "magenta" }
exec    = { fg = "cyan" }
desc    = { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer  = { fg = "black", bg = "white" }

[notify]
title_info  = { fg = "green" }
title_warn  = { bg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "cyan" },

	# Videos
	{ mime = "video/*", fg = "yellow" },
	{ mime = "audio/*", fg = "yellow" },

	# Archives
	{ mime = "application/zip",             fg = "magenta" },
	{ mime = "application/gzip",            fg = "magenta" },
	{ mime = "application/x-tar",           fg = "magenta" },
	{ mime = "application/x-bzip",          fg = "magenta" },
	{ mime = "application/x-bzip2",         fg = "magenta" },
	{ mime = "application/x-7z-compressed", fg = "magenta" },
	{ mime = "application/x-rar",           fg = "magenta" },
	{ mime = "application/xz",              fg = "magenta" },

	# Documents
	{ mime = "application/doc",   fg = "green" },
	{ mime = "application/pdf",   fg = "green" },
	{ mime = "application/rtf",   fg = "green" },
	{ mime = "application/vnd.*", fg = "green" },

	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "blue" }
]

[icon]

rules = [
	# Programming
	{ name = "*.c"    , text = "", fg = "#7E9CD8" },
	{ name = "*.cpp"  , text = "", fg = "#7FB4CA" },
	{ name = "*.css"  , text = "", fg = "#42a5f5" },
	{ name = "*.go"   , text = "", fg = "#7FB4CA" },
	{ name = "*.h"    , text = "", fg = "#957FB8" },
	{ name = "*.hpp"  , text = "", fg = "#957FB8" },
	{ name = "*.html" , text = "", fg = "#FF5D62" },
	{ name = "*.lua"  , text = "", fg = "#51a0cf" },
	{ name = "*.nix"  , text = "", fg = "#A3D4D5" },
	{ name = "*.py"   , text = "", fg = "#DCA561" },
	{ name = "*.rs"   , text = "", fg = "#FFA066" },
	{ name = "*.scss" , text = "", fg = "#D27E99" },
	{ name = "*.sh"   , text = "", fg = "#727169" },

	# Text
	{ name = "*.conf", text = "", fg = "#717C7C" },
	{ name = "*.ini" , text = "", fg = "#717C7C" },
	{ name = "*.json", text = "", fg = "#7AA880" },
	{ name = "*.md"  , text = "", fg = "#ffffff" },
	{ name = "*.toml", text = "", fg = "#ffffff" },
	{ name = "*.txt" , text = "", fg = "#98BB6C" },
	{ name = "*.yaml", text = "", fg = "#717C7C" },
	{ name = "*.yml" , text = "", fg = "#717C7C" },

	# Archives
	{ name = "*.7z" , text = "" },
	{ name = "*.bz2", text = "" },
	{ name = "*.gz" , text = "" },
	{ name = "*.rar", text = "" },
	{ name = "*.tar", text = "" },
	{ name = "*.xz" , text = "" },
	{ name = "*.zip", text = "" },

	# Images
	{ name = "*.HEIC", text = "", fg = "#957FB8" },
	{ name = "*.avif", text = "", fg = "#957FB8" },
	{ name = "*.bmp" , text = "", fg = "#957FB8" },
	{ name = "*.gif" , text = "", fg = "#957FB8" },
	{ name = "*.ico" , text = "", fg = "#7AA880" },
	{ name = "*.jpeg", text = "", fg = "#957FB8" },
	{ name = "*.jpg" , text = "", fg = "#957FB8" },
	{ name = "*.png" , text = "", fg = "#957FB8" },
	{ name = "*.svg" , text = "", fg = "#FF9E3B" },
	{ name = "*.webp", text = "", fg = "#957FB8" },

	# Movies
	{ name = "*.avi" , text = "", fg = "#FF9E3B" },
	{ name = "*.mkv" , text = "", fg = "#FF9E3B" },
	{ name = "*.mov" , text = "", fg = "#FF9E3B" },
	{ name = "*.mp4" , text = "", fg = "#FF9E3B" },
	{ name = "*.webm", text = "", fg = "#FF9E3B" },

	# Audio
	{ name = "*.aac" , text = "", fg = "#A3D4D5" },
	{ name = "*.flac", text = "", fg = "#A3D4D5" },
	{ name = "*.m4a" , text = "", fg = "#A3D4D5" },
	{ name = "*.mp3" , text = "", fg = "#A3D4D5" },
	{ name = "*.ogg" , text = "", fg = "#A3D4D5" },
	{ name = "*.wav" , text = "", fg = "#A3D4D5" },

	# Documents
	{ name = "*.csv" , text = "", fg = "#98BB6C" },
	{ name = "*.doc" , text = "", fg = "#7E9CD8" },
	{ name = "*.doct", text = "", fg = "#7E9CD8" },
	{ name = "*.docx", text = "", fg = "#7E9CD8" },
	{ name = "*.dot" , text = "", fg = "#7E9CD8" },
	{ name = "*.pdf" , text = "", fg = "#43242B" },
	{ name = "*.pom" , text = "", fg = "#C34043" },
	{ name = "*.pot" , text = "", fg = "#C34043" },
	{ name = "*.potx", text = "", fg = "#C34043" },
	{ name = "*.ppm" , text = "", fg = "#957FB8" },
	{ name = "*.ppmx", text = "", fg = "#C34043" },
	{ name = "*.pps" , text = "", fg = "#C34043" },
	{ name = "*.ppsx", text = "", fg = "#C34043" },
	{ name = "*.ppt" , text = "", fg = "#C34043" },
	{ name = "*.pptx", text = "", fg = "#C34043" },
	{ name = "*.xlc" , text = "", fg = "#7AA880" },
	{ name = "*.xlm" , text = "", fg = "#7AA880" },
	{ name = "*.xls" , text = "", fg = "#7AA880" },
	{ name = "*.xlsm", text = "", fg = "#7AA880" },
	{ name = "*.xlsx", text = "", fg = "#7AA880" },
	{ name = "*.xlt" , text = "", fg = "#7AA880" },

	# Lockfiles
	{ name = "*.lock", text = "", fg = "#DCD7BA" },

	# Misc
	{ name = "*.bin", text = "", fg = "#E82424" },
	{ name = "*.exe", text = "", fg = "#E82424" },
	{ name = "*.pkg", text = "", fg = "#E82424" },

	# Dotfiles
	{ name = ".bashprofile"  , text = "", fg = "#98BB6C" },
	{ name = ".bashrc"       , text = "", fg = "#98BB6C" },
	{ name = ".gitattributes", text = "", fg = "#363646" },
	{ name = ".gitignore"    , text = "", fg = "#363646" },
	{ name = ".gitmodules"   , text = "", fg = "#363646" },
	{ name = ".zprofile"     , text = "", fg = "#98BB6C" },
	{ name = ".zshenv"       , text = "", fg = "#98BB6C" },
	{ name = ".zshrc"        , text = "", fg = "#98BB6C" },

	# Named files
	{ name = "COPYING"      , text = "󰿃", fg = "#7AA880" },
	{ name = "Containerfile", text = "󰡨", fg = "#7E9CD8" },
	{ name = "Dockerfile"   , text = "󰡨", fg = "#7E9CD8" },
	{ name = "LICENSE"      , text = "󰿃", fg = "#E6C384" },

	# Directories
	{ name = ".config/"    , text = "" },
	{ name = ".git/"       , text = "" },
	{ name = "Desktop/"    , text = "" },
	{ name = "Development/", text = "" },
	{ name = "Documents/"  , text = "" },
	{ name = "docs/"  , text = "" },
	{ name = "downloads/"  , text = "" },
	{ name = "Library/"    , text = "" },
	{ name = "Movies/"     , text = "" },
	{ name = "Music/"      , text = "" },
	{ name = "Pictures/"   , text = "" },
	{ name = "pics/"   , text = "" },
	{ name = "screenshots/"   , text = "" },
	{ name = "Public/"     , text = "" },
	{ name = "Videos/"     , text = "" },

	# Default
	{ name = "*" , text = "" },
	{ name = "*/", text = "" },
]
